version: "3"
services:
  telegram-unban-removed-users-bot:
    image: systemnick/telegram-unban-removed-users-bot:latest
    hostname: telegram-unban-removed-users-bot
    restart: always
    container_name: telegram-unban-removed-users-bot
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      - TELEGRAM_TOKEN
      - ADMIN_GROUP_ID
